config/routes.rb
ReefSense::Application.routes.draw do
  resources :alarm_histories

  get "pictures/step_1"
  get "pictures/step_2"
  resources :pictures


  resources :galleries


  resources :demos


  resources :notifications


  resources :equipment


  resources :user_equipments


  resources :update_codes


  resources :livestocks


  resources :user_livestocks


  resources :livestock_imports
  get "reef_tanks/hourly"
  get "reef_tanks/my_tank"
  get "reef_tanks/setting"
  resources :reef_tanks
 


   authenticated :user do
    #root :to => "reef_tanks#index"
    root :to => "reef_tanks#my_tank"
   end


  root :to => "demos#home"

  resources :maintainence_logs


  resources :arduinos


  resources :watchers


  resources :todo_tasks


  resources :todo_lists


 
  devise_for :users
  resources :users
end

app/models/todo_task.rb
class TodoTask < ActiveRecord::Base
  attr_accessible :completed, :description, :list_id, :reef_tank_id
end

app/controllers/todo_tasks_controller.rb
class TodoTasksController < ApplicationController
  # GET /todo_tasks
  # GET /todo_tasks.json
  def index
    @todo_tasks = TodoTask.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todo_tasks }
    end
  end

  # GET /todo_tasks/1
  # GET /todo_tasks/1.json
  def show
    @todo_task = TodoTask.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @todo_task }
    end
  end

  # GET /todo_tasks/new
  # GET /todo_tasks/new.json
  def new
    @todo_task = TodoTask.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo_task }
    end
  end

  # GET /todo_tasks/1/edit
  def edit
    @todo_task = TodoTask.find(params[:id])
  end

  # POST /todo_tasks
  # POST /todo_tasks.json
  def create
    @todo_task = TodoTask.new(params[:todo_task])

    respond_to do |format|
      if @todo_task.save
        format.html { redirect_to @todo_task, notice: 'Todo task was successfully created.' }
        format.json { render json: @todo_task, status: :created, location: @todo_task }
      else
        format.html { render action: "new" }
        format.json { render json: @todo_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todo_tasks/1
  # PUT /todo_tasks/1.json
  def update
    @todo_task = TodoTask.find(params[:id])

    respond_to do |format|
      if @todo_task.update_attributes(params[:todo_task])
        format.html { redirect_to @todo_task, notice: 'Todo task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_tasks/1
  # DELETE /todo_tasks/1.json
  def destroy
    @todo_task = TodoTask.find(params[:id])
    @todo_task.destroy

    respond_to do |format|
      format.html { redirect_to todo_tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/todo_tasks_helper.rb
module TodoTasksHelper
end

app/views/todo_tasks/_form.html.erb
<%= simple_form_for @todo_task, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :reef_tank_id %>
  <%= f.input :list_id %>
  <%= f.input :description %>
  <%= f.input :completed %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                todo_tasks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/todo_tasks/edit.html.erb
<%- model_class = TodoTask -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todo_tasks/index.html.erb
<%- model_class = TodoTask -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:reef_tank_id) %></th>
      <th><%= model_class.human_attribute_name(:list_id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:completed) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @todo_tasks.each do |todo_task| %>
      <tr>
        <td><%= link_to todo_task.id, todo_task_path(todo_task) %></td>
        <td><%= todo_task.reef_tank_id %></td>
        <td><%= todo_task.list_id %></td>
        <td><%= todo_task.description %></td>
        <td><%= todo_task.completed %></td>
        <td><%=l todo_task.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_todo_task_path(todo_task), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      todo_task_path(todo_task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_todo_task_path,
            :class => 'btn btn-primary' %>

app/views/todo_tasks/new.html.erb
<%- model_class = TodoTask -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todo_tasks/show.html.erb
<%- model_class = TodoTask -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:reef_tank_id) %>:</strong></dt>
  <dd><%= @todo_task.reef_tank_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:list_id) %>:</strong></dt>
  <dd><%= @todo_task.list_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @todo_task.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:completed) %>:</strong></dt>
  <dd><%= @todo_task.completed %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              todo_tasks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_todo_task_path(@todo_task), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              todo_task_path(@todo_task),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>