config/routes.rb
ReefSense::Application.routes.draw do
  resources :alarm_histories

  get "pictures/step_1"
  get "pictures/step_2"
  resources :pictures


  resources :galleries


  resources :demos


  resources :notifications


  resources :equipment


  resources :user_equipments


  resources :update_codes


  resources :livestocks


  resources :user_livestocks


  resources :livestock_imports
  get "reef_tanks/hourly"
  get "reef_tanks/my_tank"
  get "reef_tanks/setting"
  resources :reef_tanks
 


   authenticated :user do
    #root :to => "reef_tanks#index"
    root :to => "reef_tanks#my_tank"
   end


  root :to => "demos#home"

  resources :maintainence_logs


  resources :arduinos


  resources :watchers


  resources :todo_tasks


  resources :todo_lists


 
  devise_for :users
  resources :users
end

app/models/arduino.rb
class Arduino < ActiveRecord::Base
  attr_accessible :arduino_board_type, :parameter_setup, :reef_tank_arduino_id, :reef_tank_id
end

app/controllers/arduinos_controller.rb
class ArduinosController < ApplicationController
  # GET /arduinos
  # GET /arduinos.json
  def index
    @arduinos = Arduino.all
     # @user = current_user.id
     # @arduinos = Arduino.where(:reef_tank_id => @user) #(:reef_tank_id => params[:reef_tank_id])
     

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @arduinos }
    end
  end

  # GET /arduinos/1
  # GET /arduinos/1.json
  def show
    @arduino = Arduino.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @arduino }
    end
  end

  # GET /arduinos/new
  # GET /arduinos/new.json
  def new
    @arduino = Arduino.new(:reef_tank_id => params[:reef_tank_id])
    # @reef_tank = ReefTank.new(:reef_tank_id => params[:reef_tank_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @arduino }
    end
  end

  # GET /arduinos/1/edit
  def edit
    @arduino = Arduino.find(params[:id])
  end

  # POST /arduinos
  # POST /arduinos.json
  def create
    #@reef_tank = ReefTank.new(params[:reef_tank])
    @arduino = Arduino.new(params[:arduino])

    respond_to do |format|
      if @arduino.save
        format.html { redirect_to @arduino, notice: 'A Arduino System was successfully created.' }
        format.json { render json: @arduino, status: :created, location: @arduino }
      else
        format.html { render action: "new" }
        format.json { render json: @arduino.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /arduinos/1
  # PUT /arduinos/1.json
  def update
    @arduino = Arduino.find(params[:id])

    respond_to do |format|
      if @arduino.update_attributes(params[:arduino])
        format.html { redirect_to @arduino, notice: 'Arduino was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @arduino.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arduinos/1
  # DELETE /arduinos/1.json
  def destroy
    @arduino = Arduino.find(params[:id])
    @arduino.destroy

    respond_to do |format|
      format.html { redirect_to arduinos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/arduinos_helper.rb
module ArduinosHelper
end

app/views/arduinos/_form.html.erb
<%= simple_form_for @arduino, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :reef_tank_id %>
  <%= f.input :parameter_setup, :input_html => { :class => "enroll_input span4", :rows => 2}  %>
  <%= f.input :reef_tank_arduino_id %>
  <%= f.input :arduino_board_type %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                arduinos_path, :class => 'btn' %>
  </div>
<% end %>

app/views/arduinos/edit.html.erb
<%- model_class = Arduino -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/arduinos/index.html.erb
<%- model_class = Arduino -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:reef_tank_id) %></th>
      <th><%= model_class.human_attribute_name(:parameter_setup) %></th>
      <th><%= model_class.human_attribute_name(:reef_tank_arduino_id) %></th>
      <th><%= model_class.human_attribute_name(:arduino_board_type) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @arduinos.each do |arduino| %>
      <tr>
        <td><%= link_to arduino.id, arduino_path(arduino) %></td>
        <td><%= arduino.reef_tank_id %></td>
        <td><%= arduino.parameter_setup %></td>
        <td><%= arduino.reef_tank_arduino_id %></td>
        <td><%= arduino.arduino_board_type %></td>
        <td><%=l arduino.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_arduino_path(arduino), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      arduino_path(arduino),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_arduino_path,
            :class => 'btn btn-primary' %>

app/views/arduinos/new.html.erb
<%- model_class = Arduino -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
<%= debug @arduinos  if Rails.env.development?%>
<%= debug(params) if Rails.env.development? %>

app/views/arduinos/show.html.erb
<%- model_class = Arduino -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:reef_tank_id) %>:</strong></dt>
  <dd><%= @arduino.reef_tank_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:parameter_setup) %>:</strong></dt>
  <dd><%= @arduino.parameter_setup %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reef_tank_arduino_id) %>:</strong></dt>
  <dd><%= @arduino.reef_tank_arduino_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:arduino_board_type) %>:</strong></dt>
  <dd><%= @arduino.arduino_board_type %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              arduinos_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_arduino_path(@arduino), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              arduino_path(@arduino),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>