config/routes.rb
ReefSense::Application.routes.draw do
  resources :alarm_histories

  get "pictures/step_1"
  get "pictures/step_2"
  resources :pictures


  resources :galleries


  resources :demos


  resources :notifications


  resources :equipment


  resources :user_equipments


  resources :update_codes


  resources :livestocks


  resources :user_livestocks


  resources :livestock_imports
  get "reef_tanks/hourly"
  get "reef_tanks/my_tank"
  get "reef_tanks/setting"
  resources :reef_tanks
 


   authenticated :user do
    #root :to => "reef_tanks#index"
    root :to => "reef_tanks#my_tank"
   end


  root :to => "demos#home"

  resources :maintainence_logs


  resources :arduinos


  resources :watchers


  resources :todo_tasks


  resources :todo_lists


 
  devise_for :users
  resources :users
end

app/models/reef_tank.rb
class ReefTank < ActiveRecord::Base
  include Tokenable
  attr_accessible :measurement_type, :send_email_okay, :tank_name, :setup_date, :size, :user_id, :arduino_board_type, :parameter_setup, :reef_tank_arduino_id, :reef_tank_id
  
  belongs_to :user
  
  validates :user_id, presence: true
  
  has_many :demos
  has_many :todo_lists
  has_many :watchers, :foreign_key => :reef_tank_arduino_id, :primary_key =>  :reef_tank_arduino_id
 # has_many :update_codes, through: :watchers
   has_many :update_codes, :foreign_key => :reef_tank_arduino_id, :primary_key =>  :reef_tank_arduino_id
  has_many :maintainence_logs
  has_many :user_equipments 
  has_many :notifications, :foreign_key => :reef_tank_id, :primary_key =>  :id, :inverse_of => :reef_tank, :dependent => :destroy
  
  has_many :pictures, :foreign_key => :reef_tank_id
  has_many :user_livestocks
 
  

end

app/controllers/reef_tanks_controller.rb
class ReefTanksController < ApplicationController
  # GET /reef_tanks
  # GET /reef_tanks.json
  
 #  before_filter :authenticate_user!, :except => [:hourly]
  
  
  def hourly
   
    stats  = Watcher.all
    
    #stats = Stat.hourly(params[:stat_type])
    respond_to do |format|
      format.json do
        datapoints = []
        stats.each do |stat|
          datapoints << {:title => "temp", :value => stat.temp}
        end
        datasequences = [
          {
            :title => 'Hourly count',
            :datapoints => datapoints
          }
        ]
        graph = {
          :title => I18n.t("stat_types.for_#{params[:stat_type]}"),
          :total => true,
          :color => "blue",
          :datasequences => datasequences
        }
        render :json => {:graph => graph}
      end
    end
  end
  
  
  
  def my_tank
     @user = current_user.id
      @reef_tank = ReefTank.where(:user_id => @user).last 
 
   
     respond_to do |format|
       format.html # index.html.erb
       format.json { render json: @reef_tanks }
     end
    
    
    
  end
  
  def setting
      @user = current_user.id
      @reef_tank = ReefTank.where(:user_id => @user).last
      
 
      
      
      
    #@reef_tank = ReefTank.find(params[:id])
    # @reef_tank = ReefTank.where(:id => @reef_tank)
    #@reef_tank = ReefTank.find(params[:id])
  
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reef_tanks }
    end
  end
  
  def index
    @user = current_user.id
    @reef_tanks = ReefTank.where(:user_id => @user)
  
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reef_tanks }
    end
  end

  # GET /reef_tanks/1
  # GET /reef_tanks/1.json
  def show
    @reef_tank = ReefTank.find(params[:id])
     @watchers = Watcher.all
     
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reef_tank }
    end
  end

  # GET /reef_tanks/new
  # GET /reef_tanks/new.json
  def new
  
    @reef_tank = ReefTank.new(:user_id => params[:user_id])


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reef_tank }
    end
  end

  # GET /reef_tanks/1/edit
  def edit
    @reef_tank = ReefTank.find(params[:id])
  end

  # POST /reef_tanks
  # POST /reef_tanks.json
  def create
    @reef_tank = ReefTank.new(params[:reef_tank])
   # @reef_tank  = @user.reef_tanks.build(params[:reef_tank])
    

    respond_to do |format|
      if @reef_tank.save
        format.html { redirect_to @reef_tank, notice: 'Reef tank was successfully created.' }
        format.json { render json: @reef_tank, status: :created, location: @reef_tank }
      else
        format.html { render action: "new" }
        format.json { render json: @reef_tank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reef_tanks/1
  # PUT /reef_tanks/1.json
  def update
    @reef_tank = ReefTank.find(params[:id])

    respond_to do |format|
      if @reef_tank.update_attributes(params[:reef_tank])
        format.html { redirect_to @reef_tank, notice: 'Reef tank was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reef_tank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reef_tanks/1
  # DELETE /reef_tanks/1.json
  def destroy
    @reef_tank = ReefTank.find(params[:id])
    @reef_tank.destroy

    respond_to do |format|
      format.html { redirect_to reef_tanks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reef_tanks_helper.rb
module ReefTanksHelper
  
  def status_alarm_code(watcher)

 if watcher.update_codes  !=nil
   for update_code in watcher.update_codes  
  			 if watcher.updated_reason.to_i == update_code.reef_tank_id.to_i 
  				
  				 @code =  content_tag(:p, "#{update_code.message}")           
  		 
  			 	 else
          #@code = content_tag(:div, content_tag(:span, "No Code Setup"), class: "label label-default")
           #return content_tag(:div,   content_tag(:span, link_to('No Code Setup', new_update_code_path ), :class => 'label label-default'))
        	 end
  			 	 
  		  end  
        else
        content_tag(:div, content_tag(:span, "No Data"), class: "label label-default")  
       end
       
       
       return @code
       
       
  end
  
  
 
  def status_powerhead(watcher)

    if watcher.powerhead !=nil

   if watcher.powerhead?     #home_address == false 
     content_tag(:div, content_tag(:span, "ON"), class: "label label-success")
   else
     content_tag(:div, content_tag(:span, "OFF"), class: "label label-warning")   
   end
   
   else
   content_tag(:div, content_tag(:span, "No Data"), class: "label label-default")  
  end
  
 end
  
  
  def status_mainpump(watcher)

    if watcher.main_pump !=nil
      
    if watcher.main_pump?
      content_tag(:div, content_tag(:span, "ON"), class: "label label-success")
    else
      content_tag(:div, content_tag(:span, "OFF"), class: "label label-warning")   
    end
    
      else
        
      content_tag(:div, content_tag(:span, "No Data"), class: "label label-default")  
   end
  
  end
 
  
  def status_skimmer(watcher)

   if watcher.skimmer !=nil
    
         if watcher.skimmer?     #home_address == false 
           content_tag(:div, content_tag(:span, "ON"), class: "label label-success")
         else
           content_tag(:div, content_tag(:span, "OFF"), class: "label label-warning")   
         end
  
  
      else
        
      content_tag(:div, content_tag(:span, "No Data"), class: "label label-default")  

     
   end
    
    
  end
  
  
  def status_refuge_light(watcher)


    if watcher.refuge_light !=nil

     if watcher.refuge_light?     #home_address == false 
       content_tag(:div, content_tag(:span, "ON"), class: "label label-success")
     else
       content_tag(:div, content_tag(:span, "OFF"), class: "label label-warning")   
     end
     
     
       else
       content_tag(:div, content_tag(:span, "No Data"), class: "label label-default")  
      end
   end
  
  def status_atopump(watcher)


    if watcher.ato_pump !=nil

     if watcher.ato_pump?     #home_address == false 
       content_tag(:div, content_tag(:span, "ON"), class: "label label-success")
     else
       content_tag(:div, content_tag(:span, "OFF"), class: "label label-warning")   
     end
     
     
       else
       content_tag(:div, content_tag(:span, "No Data"), class: "label label-default")  
      end
   end
  
  
  def status_heater(watcher)
    
    
    if watcher.heater !=nil

    if watcher.heater?     #home_address == false 
      content_tag(:div, content_tag(:span, "ON"), class: "label label-success")
    else
      content_tag(:div, content_tag(:span, "OFF"), class: "label label-warning")   
    end
    
      else
      content_tag(:div, content_tag(:span, "No Data"), class: "label label-default")  
     end
  end
  
  
  
  
  def status_waterlevelokay(watcher)


    if watcher.waterlevelokay !=nil

    if watcher.waterlevelokay?     
  
     content_tag(:div, content_tag(:span, "Water Level low"), class: "label label-warning")  
    else
       content_tag(:div, content_tag(:span, "Okay"), class: "label label-success") 
       
    end
    
      else
      content_tag(:div, content_tag(:span, "No Data"), class: "label label-default")  
     end
  end
  
  def status_ph_level(watcher)
    
    
    if watcher.ph_level !=nil

    if watcher.ph_level?    
      content_tag(:div, content_tag(:span, "not setup"), class: "label label-success")
    else
      content_tag(:div, content_tag(:span, "not setup"), class: "label label-warning")   
    end
    
      else
      content_tag(:div, content_tag(:span, "No Data"), class: "label label-default")  
     end
  end
  
  
  def status_chiller(watcher)
    
    
    if watcher.chiller !=nil

    if watcher.chiller?     #home_address == false 
      content_tag(:div, content_tag(:span, "ON"), class: "label label-success")
    else
      content_tag(:div, content_tag(:span, "OFF"), class: "label label-warning")   
    end
    
      else
      content_tag(:div, content_tag(:span, "No Data"), class: "label label-default")  
     end
  end
  
  def status_refuge_light(watcher)
    
    
    if watcher.refuge_light !=nil

    if watcher.refuge_light?     #home_address == false 
      content_tag(:div, content_tag(:span, "ON"), class: "label label-success")
    else
      content_tag(:div, content_tag(:span, "OFF"), class: "label label-warning")   
    end
    
      else
      content_tag(:div, content_tag(:span, "No Data"), class: "label label-default")  
     end
  end
  
  def status_temp(watcher)
    
    
    if watcher.temp !=nil 
 
      content_tag(:p, "#{number_with_precision(watcher.temp, :precision => 1)}#{176.chr(Encoding::UTF_8)}f") 
     
      else
   
      content_tag(:div, content_tag(:span, "No Data"), class: "label label-default")  
     end
  end
  
  
 
  
  
  
   def status_ambeint_temp(watcher)


     if watcher.ambeint_temp !=nil 
        content_tag(:p, "#{number_with_precision(watcher.ambeint_temp, :precision => 1)}#{176.chr(Encoding::UTF_8)}f") 
      
       else
       content_tag(:div, content_tag(:span, "No Data"), class: "label label-default")  
      end
   end
   
   def status_last_updated(watcher)

  
     if watcher.created_at !=nil
      content_tag(:p, "#{time_ago_in_words(watcher.created_at)} ago") 
       else
       content_tag(:div, content_tag(:span, "No Data"), class: "label label-default")  
      end
   end
 
   def status_send_email_okay(watcher)


     if watcher.send_email.okay !=nil

     if watcher.send_email.okay?     #home_address == false 
       content_tag(:div, content_tag(:span, "ON"), class: "label label-success")
     else
       content_tag(:div, content_tag(:span, "OFF"), class: "label label-warning")   
     end

       else
       content_tag(:div, content_tag(:span, "No Data"), class: "label label-default")  
      end
   end
 
 
 
 
 
end

app/views/reef_tanks/_current_status.html.erb
<% @current_status = @reef_tank.watchers.order("created_at").first %>

<table class="table table-striped">
  <thead>
<tr style="border-top: 0px solid #eee; padding-top: 5px; margin-top: 5px">
	
	<strong></strong>
	
	<div class="fancy-date">
		Last Updated:
		<% if (@current_status != nil) then %>
			 <%= time_ago_in_words(@current_status.created_at) %>  ago  
		<% else %>
		<% end %>	
	 </div>	

	 </td>

	</tr>
	
	
	<tr>
  <td class="fancy-date ">
	
	
  <div class="fancy-weekday, fancy-date ">
	
 Temp
</div>
<div class="fancy-day">
  	<% if (@current_status != nil) then %>
	 <%= number_with_precision(@current_status.temp, :precision => 1)   %>°f
	<% else %>
	<% end %>
       
 </div>
 </td>

</tr>
                             

</thead>
</table>
 
 
 
   
 

app/views/reef_tanks/_form.html.erb
<%= simple_form_for @reef_tank, :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id   } %>
 
  <%= f.input :setup_date %>
 <%= f.input :tank_name %> 
  <%= f.input :size %>
  <%= f.input :measurement_type %>
  <%= f.input :send_email_okay %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                reef_tanks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/reef_tanks/_my_reef_tank.html.erb
<%- model_class = ReefTank -%>
<div class="page-header">
  <h1>Chris' Rimless 30g Cube </h1>
</div>


  

<dl class="dl-horizontal">
  <dt><strong>User:</strong></dt>
  <dd><%= @reef_tank.user_id %></dd>
  <dt><strong>Setup tank:</strong></dt>
  <dd><%= time_ago_in_words(@reef_tank.setup_date)%> ago</dd>
  <dt><strong>Receieve Email:</strong></dt>
  <dd><%= @reef_tank.send_email_okay %></dd>
  <dt><strong>Arduino Unique Code:</strong></dt>
  <dd><%= @reef_tank.reef_tank_arduino_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_reef_tank_path(@reef_tank), :class => 'btn' %>
</div>

app/views/reef_tanks/_my_update_code.html.erb
<% @update_codes = @reef_tank.update_codes.paginate(page: params[:page], :per_page => 5) %>
 
<div class="page-header">
  <h3>Arduino Reason for Update Codes:</h3>
</div>	
<table class="table table-striped">
  <thead>
    <tr> <th>Code:</th>
      <th>Alarm ID</th>
      <th>Tank Code</th>
       
 
      <th>Send Email</th>

      <th>Message</th>
   
      <th>Display Site Wide</th>

      
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>


  <tbody>
    
  <% @update_codes.each do |update_code| %>
      <tr>
      	 <td><%= link_to update_code.id, update_code_path(update_code) %></td>
	        <td><%= update_code.reef_tank_id %></td>
	        <td><%= update_code.reef_tank_arduino_id %></td>
	        <td><%= update_code.sent_email %></td>
	        <td><%= update_code.message %></td>
	   
	        <td><%= update_code.display_site_wide %></td>
                

        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_update_code_path(update_code), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      update_code_path(update_code),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_update_code_path,
            :class => 'btn btn-primary' %>


 <%= will_paginate @update_codes %>
 <br>
<br>

app/views/reef_tanks/_my_watcher.html.erb
<% @watchers = @reef_tank.watchers.order("created_at").paginate(page: params[:page], :per_page => 5) %>

<%= debug @watchers if Rails.env.development? %>

 

<div class="page-header">
  <h3>Real Time Data History: </h3>
</div>	
<table class="table table-striped">
  <thead>
    <tr> <th>Code:</th>
      <th>ID</th>
      <th>Name</th>
 
      <th>House</th>

      <th>Powerhead</th>
      <th>Main Pump</th>
      <th>Heater</th>
	   <th>ATO Pump</th>
      <th>Water Level</th>
<th>Refuge Light</th>
     <th>Received</th>
      
    </tr>
  </thead>


  <tbody>
    <% @watchers.each do |watcher| %>
  
 

      <tr>
         <td><%= status_alarm_code(watcher)  %></td>
		
        <td><%= link_to watcher.id, watcher_path(watcher) %></td>
     <td><%= status_temp(watcher)  %></td>
     <td><%= status_ambeint_temp(watcher)  %></td>
     <td>	
	<%= status_powerhead(watcher)  %>
	</td>
	<td>
    <%= status_mainpump(watcher)  %>
    </td>
	<td>
	 <%= status_heater(watcher)  %>
	 </td>
	
	<td>
	 <%= status_atopump(watcher)  %>
	 </td>
 
	<td>
	 <%= status_waterlevelokay(watcher)  %>
	 </td>   
		
	 
		<td>
		 <%= status_refuge_light(watcher)  %>
		 </td>
		<td> <%= status_last_updated(watcher)  %> </td>

       
      </tr>
    <% end %>
  </tbody>
</table>



 <%= will_paginate @watchers %>

        

app/views/reef_tanks/_notification.html.erb
<% @notifications = @reef_tank.notifications %>
 
<div class="page-header">
  <h3>Temperature Notification Settings:</h3>
</div>	
<table class="table table-striped">
  <thead>
    <tr> 
    	<th>Notification #:</th>
        <th>Value</th>
	<th>check_parameter</th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>


  <tbody>
    
  <% @notifications.each do |notification| %>
      <tr>
      	 <td><%= link_to notification.id, notification_path(notification) %></td>
	 <td><%= notification.sent_email %></td>
         <td><%= notification.check_parameter %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_notification_path(notification), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      notification_path(notification),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_notification_path(:reef_tank => @reef_tank.id),
            :class => 'btn btn-primary' %>


 
 <br>
<br>

app/views/reef_tanks/edit.html.erb
<%- model_class = ReefTank -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/reef_tanks/index.html.erb
<%- model_class = ReefTank -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:setup_date) %></th>
      <th><%= model_class.human_attribute_name(:size) %></th>
      <th><%= model_class.human_attribute_name(:measurement_type) %></th>
      <th><%= model_class.human_attribute_name(:send_email_okay) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reef_tanks.each do |reef_tank| %>
      <tr>
        <td><%= link_to reef_tank.id, reef_tank_path(reef_tank) %></td>
        <td><%= reef_tank.user_id %></td>
        <td><%= reef_tank.setup_date %></td>
        <td><%= reef_tank.size %></td>
        <td><%= reef_tank.measurement_type %></td>
        <td><%= reef_tank.send_email_okay %></td>
        <td><%=l reef_tank.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_reef_tank_path(reef_tank), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      reef_tank_path(reef_tank),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= debug @reef_tanks %>
<%= debug(params) if Rails.env.development? %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_reef_tank_path(:user_id => @user),
            :class => 'btn btn-primary' %>

app/views/reef_tanks/my_tank.html.erb
<%- model_class = ReefTank -%>
<div class="hidden-phone">
<!-- Jumbotron -->
     <div class="jumbotron">
       <h1>Reef Sense</h1>
       <p class="lead">Real Time Data, Alarm Notification and continually real time monitoring </p>
       <a class="btn btn-large btn-success" href="#">Check out the Real Time Data</a>
     </div>
</div>
     <hr>
<% @current_status = @reef_tank.watchers.order("created_at").first %>


     <!-- Example row of columns -->
     <div class="row-fluid">
       <div class="span4">
         <h2>Temperature</h2>
         <p>  
	
	
	
			<table class="table table-striped">
			  <tbody>
			    <tr>
					<td>Temp</td>
				      <td>
					
					<%= status_temp(@current_status)  %>

								</td>

				     </tr>
				
				
					
						 <tr>
								<td>Heater</td>
							      <td>
						<%= status_heater(@current_status)  %></td>

							     </tr>
									<tr>
										<td>Last Updated</td>
									      <td>
											<%= status_last_updated(@current_status)  %> </td>
									     </tr>

	  </tbody>
	</table>
	
	</p>
         <p><%= link_to t('.View details', :default => t("helpers.links.View details")),
		              reef_tanks_setting_path, :class => 'btn'  %></p>
       </div>
       <div class="span4">
         <h2>Pump Status</h2>
         <p> 
			<table class="table table-striped">
			  <tbody>
			    <tr>
					<td>PowerHead</td>
				  		<td>	
						<%= status_powerhead(@current_status)  %>
						</td></tr>
					<tr>
						<td>Pump</td>
					   		<td>
						    <%= status_mainpump(@current_status)  %>
						    </td>
					     </tr>
						<tr>
						<td>Skimmer</td>
						<td>
						<%= status_skimmer(@current_status)  %>
						</td>
						</tr>
	    
	  </tbody>
	</table>
	
	 </p>
         <p> 
	
		  <%= link_to t('.View details', :default => t("helpers.links.View details")),
		              reef_tanks_setting_path, :class => 'btn'  %>
	</p>
      </div>
       <div class="span4">
         <h2>Water Level</h2>
         <p>	<table class="table table-striped">
			  <tbody>
			    <tr>
					<td>Water Level</td>
				      <td><%= status_waterlevelokay(@current_status)%></td>
				     </tr>
					<tr>
						<td>ATO Pump</td>
					   	<td>
						 <%= status_atopump(@current_status)  %>
						 </td>
					     </tr>
					
							<tr>
									<td>Refuge Light</td>
								   	<td>
										<%= status_refuge_light(@current_status)  %>
										 </td>
								     </tr>
						
			

	  </tbody>
	</table></p>
         <p><%= link_to t('.View details', :default => t("helpers.links.View details")),
		              reef_tanks_setting_path, :class => 'btn'  %></p>
       </div>
     </div>

  

 

app/views/reef_tanks/new.html.erb
<%- model_class = ReefTank -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>
<%= debug @reef_tanks  if Rails.env.development?%>
<%= debug(params) if Rails.env.development? %>

app/views/reef_tanks/setting.html.erb
<%= render :partial => 'my_reef_tank' , :reef_tank => @reef_tank %>

<% @pictures = @reef_tank.pictures.all %>
<div id="pictures">
  <%= render @pictures %>
</div>
 
 

<%= link_to "Add a Picture", pictures_step_1_path(:reef_tank_id => @reef_tank) %>

<%= render :partial => 'my_watcher' , :reef_tank => @reef_tank %>

<%= render :partial => 'notification' , :reef_tank => @reef_tank %> 
 
<%= render :partial => 'my_update_code' , :reef_tank => @reef_tank %> 	

 

 
 


 

app/views/reef_tanks/show.html.erb
<%- model_class = ReefTank -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>


 
   
<%= render :partial => 'current_status' , :reef_tank => @reef_tank %>

<dl class="dl-horizontal">
  <dt><strong>Reef Name:</strong></dt>
  <dd><%= @reef_tank.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:setup_date) %>:</strong></dt>
  <dd><%= @reef_tank.setup_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:size) %>:</strong></dt>
  <dd><%= @reef_tank.size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:measurement_type) %>:</strong></dt>
  <dd><%= @reef_tank.measurement_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:send_email_okay) %>:</strong></dt>
  <dd><%= @reef_tank.send_email_okay %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reef_tank_arduino_id) %>:</strong></dt>
  <dd><%= @reef_tank.reef_tank_arduino_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              reef_tanks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_reef_tank_path(@reef_tank), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              reef_tank_path(@reef_tank),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>



<div id="pictures">
  <% @reef_tank.pictures.each do |picture| %>
    <div class="picture">
	    <% if picture.image_processed? %>
	      <%= link_to image_tag(picture.picture_image_url(:thumb)), picture %>
	    <% else %>
	      <em>Processing...</em>
	    <% end %>
		
		
     
      <div class="name"><%= picture.name %></div>
      <div class="actions">
        <%= link_to "edit", edit_picture_path(picture) %> |
        <%= link_to "remove", picture, :confirm => 'Are you sure?', :method => :delete %>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>

 <%= link_to "Add a Picture", new_picture_path(:reef_tank_id => @reef_tank) %> 
</div>
 